### PR TITLE
Add basic gitlab support

### PR DESCRIPTION
**Pull request by plajjan**
This brings basic support for Gitlab.

It is a superset of @yisraeldov work in #32, which includes the basic sync support for GitLab. On top of that I refined the way the backend is chosen so that any URL that contains 'gitlab' will automatically use the gitlab backend, thus it matches `gitlab.com` and potential private instances with gitlab in the URL. Further I fixed so that it is possible to close issues, we sync in a few more properties and I removed deadline/due date as it was broken and would prevent the rest to work if a due date was set. Big thanks to @yisraeldov for all the groundwork! :)

I plan to merge this, probably later this week but I'm hoping someone besides me would have time to try it out before I merge to master. Feedback welcome!

### CODE REVIEW

**Comment by yisraeldov** [comment]
If we could do something to speed this up,  it takes forever if there are lots of tasks to sync. 

Also getting tags to work would be very useful

**Comment by yisraeldov** [comment]
If we could do something to speed this up,  it takes forever if there are lots of tasks to sync. 

Also getting tags to work would be very useful

**Comment by plajjan** [comment]
@yisraeldov sure, so I was thinking of merging this to master as a sort of baseline and then we could continue working on adding more features. I wanted the due date but it was broken and rather than block merging of this I slated it for later.

Dunno about speed. I have no idea how to speed this up, would need to start with profiling.. create an issue?

But have you tried this branch now, including my changes? Does it work for you? If it does I'm ready to merge this to master...

**Comment by yisraeldov** [comment]
Have not tried yet.

The speed issue is because it makes a separate request for each task, brute
force updating.

I remember seeing a way to do async http requests,  not sure if that would
help.

**Comment by plajjan** [comment]
@yisraeldov would you like to try this out before I merge to master?

**Comment by plajjan** [comment]
I've used this a bit more. Feeling fairly confident so I'm merging. :shipit:

**Comment by yisraeldov** [comment]
Great,  thanks

**Pull request merged**
