### PR TITLE
don't mark nil ids as dups

### PR DESCRIPTION
**Pull request by yisraeldov**
Fixes an issue where you can't sync more than one new task #22

### CODE REVIEW

**Comment by yisraeldov** [comment]
@arbox @plajjan Any chance to get this merged in ? With out it you can only create one new task at a time.

**Comment by plajjan** [comment]
I've tried and it appears to works correctly. I plan on merging this as part of the gitlab changes.

@yisraeldov indent is using a mix of tabs and spaces in this particular patch. Would be super if you could check your settings so any further patches are aligned with the rest of the file. Thanks for patch (I also ran into this problem when working on the gitlab patch) :)

**Comment by yisraeldov** [comment]
Oops, that is odd

**Comment by plajjan** [comment]
This change, though not this exact commit, was included in #34, that is now merged, so I'm closing this.

**Pull request closed without merging**
